import { Category, Occasion, GiftBox, StoreSettings, Product } from '../types';

export const INITIAL_CATEGORIES: Omit<Category, 'id'>[] = [
  { name: 'Perfumes', nameUrdu: 'عطر و پرفیومز', slug: 'perfumes', description: 'Exquisite oriental fragrances & artisanal attars' },
  { name: 'Watches', nameUrdu: 'گھڑیاں', slug: 'watches', description: 'Timeless luxury chronographs & couple timepieces' },
  { name: 'Wallets', nameUrdu: 'والٹس و بٹوے', slug: 'wallets', description: 'Handcrafted genuine leather wallets & cardholders' },
  { name: 'Chocolates', nameUrdu: 'چاکلیٹس', slug: 'chocolates', description: 'Gourmet artisanal Belgian truffles & dates' },
  { name: 'Mugs', nameUrdu: 'مگز و کپس', slug: 'mugs', description: 'Ceramic customized calligraphy mugs & tumblers' },
  { name: 'Flowers', nameUrdu: 'پھول و گلدستے', slug: 'flowers', description: 'Fresh long-stem red roses & everlasting floral boxes' },
  { name: 'Jewellery', nameUrdu: 'جیولری و زیورات', slug: 'jewellery', description: 'Sterling silver, zircon & gold-plated fine jewellery' },
  { name: 'Gift Boxes', nameUrdu: 'گفٹ باکسز', slug: 'gift-boxes', description: 'Curated signature gift packaging & keepsake hampers' },
  { name: 'Personalized Gifts', nameUrdu: 'کسٹمائزڈ تحائف', slug: 'personalized-gifts', description: 'Engraved pens, customized plaques & photo keepsakes' },
  { name: 'Accessories', nameUrdu: 'لوازمات و اکسیسریز', slug: 'accessories', description: 'Cufflinks, tie pins, silk scarves & brooch sets' },
  { name: 'Other Gifts', nameUrdu: 'دیگر تحائف', slug: 'other-gifts', description: 'Unique novelty gifts & customized celebration items' },
];

export const INITIAL_OCCASIONS: Omit<Occasion, 'id'>[] = [
  { name: 'Birthday', nameUrdu: 'سالگرہ', slug: 'birthday', badge: '🎉 Celebrate' },
  { name: 'Anniversary', nameUrdu: 'شادی کی سالگرہ', slug: 'anniversary', badge: '💍 Love & Milestones' },
  { name: 'Wedding', nameUrdu: 'شادی و برات', slug: 'wedding', badge: '👰 Shadi Mubarak' },
  { name: 'Engagement', nameUrdu: 'منگنی', slug: 'engagement', badge: '✨ Congratulations' },
  { name: "Valentine's Day", nameUrdu: 'ویلنٹائن ڈے', slug: 'valentines-day', badge: '❤️ Romance' },
  { name: 'Eid', nameUrdu: 'عید الاضحیٰ و الفطر', slug: 'eid', badge: '🌙 Eid Mubarak' },
  { name: "Mother's Day", nameUrdu: 'ماں کا دن', slug: 'mothers-day', badge: '🌸 For Ammi' },
  { name: "Father's Day", nameUrdu: 'والد کا دن', slug: 'fathers-day', badge: '👔 For Abu' },
  { name: 'Graduation', nameUrdu: 'گریجوایشن', slug: 'graduation', badge: '🎓 Success' },
  { name: 'Friendship', nameUrdu: 'دوستی', slug: 'friendship', badge: '🤝 Best Friends' },
  { name: 'Corporate Gifts', nameUrdu: 'کارپوریٹ تحائف', slug: 'corporate-gifts', badge: '🏢 Executive' },
  { name: 'Other Occasions', nameUrdu: 'دیگر مواقع', slug: 'other-occasions', badge: '🎁 Blessings' },
];

export const INITIAL_GIFT_BOXES: Omit<GiftBox, 'id'>[] = [
  {
    name: 'Royal Emerald Velvet Keepsake Box',
    nameUrdu: 'شاہی زمردی ویلویٹ گفٹ باکس',
    price: 1500,
    description: 'Rich deep emerald green velvet hard box with magnetic closure, satin lining, and gold foil embossed logo.',
    color: 'Emerald & Gold',
    dimensions: '30cm x 22cm x 10cm',
    imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Matte Black Luxury Executive Chest',
    nameUrdu: 'میٹ بلیک لگژری ایگزیکٹو باکس',
    price: 1800,
    description: 'Ultra-matte black rigid chest box with gold lock accent, textured finish, and crushed silk ribbon.',
    color: 'Matte Black & Gold',
    dimensions: '32cm x 24cm x 12cm',
    imageUrl: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=800&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Ivory & Rose Gold Celebration Box',
    nameUrdu: 'آئیوری اور روز گولڈ سیلیبریشن باکس',
    price: 1400,
    description: 'Classic warm ivory box embossed with delicate floral motifs and tied with a 2-inch blush rose satin bow.',
    color: 'Ivory & Rose Gold',
    dimensions: '28cm x 20cm x 9cm',
    imageUrl: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=800&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Rustic Pine Wooden Hamper Crate',
    nameUrdu: 'روایتی پائن ووڈن ہیمپر کریٹ',
    price: 2200,
    description: 'Handcrafted polished Pakistani pine wood box with brass clasp and laser-engraved calligraphy.',
    color: 'Natural Wood & Brass',
    dimensions: '35cm x 25cm x 14cm',
    imageUrl: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=800&auto=format&fit=crop&q=80',
    isActive: true,
  },
];

export const DEFAULT_STORE_SETTINGS: StoreSettings = {
  whatsappNumber: '923001234567',
  storeName: 'MINAL KHAN',
  tagline: 'Premium Gifts & Customized Gift Boxes',
  taglineUrdu: 'پریمیئم تحائف اور کسٹمائزڈ گفٹ باکسز',
  defaultLanguage: 'en',
  deliveryCharges: 250, // Standard PKR 250 delivery across Pakistan
  freeDeliveryThreshold: 4500, // Free delivery above Rs. 4,500
  contactEmail: 'orders@minalkhan.pk',
  contactPhone: '+92 300 1234567',
  address: 'Gulberg III, Lahore / Clifton, Karachi, Pakistan',
  announcement: '',
  announcementUrdu: '',
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    name: 'Royal Cambodian Dehn Al Oud',
    nameUrdu: 'شاہی کمبوڈین دہن العود',
    price: 6500,
    salePrice: 5800,
    description: 'Aged pure artisanal Cambodian Agarwood attar in a crystal decanter with velvet packaging. Unmatched oriental longevity.',
    descriptionUrdu: 'خالص دہن العود، کرسٹل بوتل اور ویلویٹ باکس کے ساتھ۔ ایک لازوال اور پروقار خوشبو۔',
    category: 'Perfumes',
    occasion: 'Eid',
    stock: 12,
    sku: 'MK-PRF-01',
    imageUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_2',
    name: 'Executive Full-Grain Leather Bi-Fold Wallet',
    nameUrdu: 'ایگزیکٹو لیدر والٹ',
    price: 3200,
    salePrice: 2850,
    description: 'Handcrafted top-grain cowhide leather wallet with RFID blocking, dual currency compartments, and custom gold initials stamping.',
    descriptionUrdu: 'خالص چمڑے سے تیار کردہ والٹ، آر ایف آئی ڈی پروٹیکشن اور شاندار فائنشنگ کے ساتھ۔',
    category: 'Wallets',
    occasion: "Father's Day",
    stock: 25,
    sku: 'MK-WLT-02',
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_3',
    name: 'His & Hers Couple Chronograph Timepiece Set',
    nameUrdu: 'کپل کلاسک کرونوگراف گھڑیاں',
    price: 9500,
    salePrice: 8500,
    description: 'Matching his and hers emerald dial quartz chronographs with stainless steel gold accents in a dual presentation box.',
    descriptionUrdu: 'جوڑوں کے لیے خوبصورت زمردی ڈائل گھڑیوں کا جوڑا، گفٹ باکس کے ساتھ۔',
    category: 'Watches',
    occasion: 'Anniversary',
    stock: 8,
    sku: 'MK-WCH-03',
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_4',
    name: 'Artisanal Belgian Truffle & Medjool Dates Box (16 Pcs)',
    nameUrdu: 'بیلجیئن چاکلیٹس و عجوہ کھجور باکس',
    price: 3800,
    description: 'Handcrafted dark and hazelnut praline Belgian truffles paired with gold-leaf stuffed organic Medjool dates in an embossed keepsake box.',
    descriptionUrdu: 'خالص بیلجیئن چاکلیٹس اور گولڈ ورق سے سجی کھجوروں کا پرتعیش تحفہ۔',
    category: 'Chocolates',
    occasion: 'Birthday',
    stock: 20,
    sku: 'MK-CHC-04',
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_5',
    name: 'Velvet Hatbox of 24 Long-Stem Red Roses',
    nameUrdu: 'لال گلابوں کا مخملی باکس',
    price: 4900,
    salePrice: 4200,
    description: 'Selected premium Dutch long-stem red roses arranged impeccably in a round black velvet hatbox tied with satin gold ribbon.',
    descriptionUrdu: 'تازہ سرخ گلابوں سے سجا بلیک ویلویٹ ہیٹ باکس، اظہار محبت کے لیے بہترین انتخاب۔',
    category: 'Flowers',
    occasion: "Valentine's Day",
    stock: 15,
    sku: 'MK-FLW-05',
    imageUrl: 'https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_6',
    name: 'Emerald Cut Zircon & 18K Gold Plated Solitaire Pendant',
    nameUrdu: 'زمردی زرکون گولڈ پلیٹڈ لاکٹ',
    price: 4500,
    salePrice: 3900,
    description: 'Radiant emerald-cut created gemstone surrounded by AAA cubic zircon halo on a 925 sterling silver 18K gold-plated chain.',
    descriptionUrdu: '۹۲۵ سٹرلنگ سلور پر ۱۸ قیراط گولڈ چڑھایا ہوا نایاب زمردی لاکٹ چین۔',
    category: 'Jewellery',
    occasion: 'Engagement',
    stock: 14,
    sku: 'MK-JWL-06',
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_7',
    name: 'Hand-Calligraphed Gold Foil Ceramic Mug & Warmer',
    nameUrdu: 'خطاطی گولڈ فوائل سیرامک مگ و وارمر',
    price: 2400,
    description: 'Handmade ceramic mug with Urdu calligraphy in 24k real gold luster, complete with smart electric temperature heating coaster.',
    descriptionUrdu: 'سونے کے پانی کی خطاطی والا سیرامک مگ اور الیکٹرک وارمر کوسٹر۔',
    category: 'Mugs',
    occasion: 'Corporate Gifts',
    stock: 30,
    sku: 'MK-MUG-07',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: false,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_8',
    name: 'Custom Engraved Brass Ballpoint Pen & Card Case',
    nameUrdu: 'کندہ شدہ قلم و کارڈ ہولڈر سیٹ',
    price: 2800,
    description: 'Heavyweight brass ballpoint pen with custom laser engraving, packaged with genuine leather pocket card holder in gift box.',
    descriptionUrdu: 'نام کندہ کرنے کی سہولت کے ساتھ پیتل کا اعلیٰ پین اور لیدر کارڈ ہولڈر۔',
    category: 'Personalized Gifts',
    occasion: 'Graduation',
    stock: 22,
    sku: 'MK-PRS-08',
    imageUrl: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: false,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
];

