import { Category, Occasion, GiftBox, StoreSettings, Product, HomepageSectionConfig, CustomerReview, BlogPost, FAQItem } from '../types';

export const INITIAL_CATEGORIES: Omit<Category, 'id'>[] = [
  { name: 'Perfumes', slug: 'perfumes', description: 'Exquisite oriental fragrances & artisanal attars', imageUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80', order: 1, isActive: true },
  { name: 'Watches', slug: 'watches', description: 'Timeless luxury chronographs & couple timepieces', imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80', order: 2, isActive: true },
  { name: 'Wallets', slug: 'wallets', description: 'Handcrafted genuine leather wallets & cardholders', imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80', order: 3, isActive: true },
  { name: 'Chocolates', slug: 'chocolates', description: 'Gourmet artisanal Belgian truffles & stuffed dates', imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80', order: 4, isActive: true },
  { name: 'Mugs', slug: 'mugs', description: 'Ceramic customized calligraphy mugs & smart warmers', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80', order: 5, isActive: true },
  { name: 'Flowers', slug: 'flowers', description: 'Fresh long-stem red roses & everlasting floral boxes', imageUrl: 'https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?w=800&auto=format&fit=crop&q=80', order: 6, isActive: true },
  { name: 'Jewellery', slug: 'jewellery', description: 'Sterling silver, zircon & gold-plated fine jewellery', imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80', order: 7, isActive: true },
  { name: 'Gift Boxes', slug: 'gift-boxes', description: 'Curated signature gift packaging & keepsake hampers', imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&auto=format&fit=crop&q=80', order: 8, isActive: true },
  { name: 'Personalized Gifts', slug: 'personalized-gifts', description: 'Engraved pens, customized plaques & photo keepsakes', imageUrl: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&auto=format&fit=crop&q=80', order: 9, isActive: true },
  { name: 'Accessories', slug: 'accessories', description: 'Cufflinks, tie pins, silk scarves & brooch sets', imageUrl: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&auto=format&fit=crop&q=80', order: 10, isActive: true },
  { name: 'Other Gifts', slug: 'other-gifts', description: 'Unique novelty gifts & customized celebration items', imageUrl: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=800&auto=format&fit=crop&q=80', order: 11, isActive: true },
];

export const INITIAL_OCCASIONS: Omit<Occasion, 'id'>[] = [
  { name: 'Birthday', slug: 'birthday', badge: '🎉 Celebrate', imageUrl: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=800&auto=format&fit=crop&q=80', order: 1, isActive: true },
  { name: 'Anniversary', slug: 'anniversary', badge: '💍 Love & Milestones', imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80', order: 2, isActive: true },
  { name: 'Wedding', slug: 'wedding', badge: '👰 Shadi Mubarak', imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=80', order: 3, isActive: true },
  { name: 'Engagement', slug: 'engagement', badge: '✨ Congratulations', imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80', order: 4, isActive: true },
  { name: "Valentine's Day", slug: 'valentines-day', badge: '❤️ Romance', imageUrl: 'https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?w=800&auto=format&fit=crop&q=80', order: 5, isActive: true },
  { name: 'Eid', slug: 'eid', badge: '🌙 Eid Mubarak', imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&auto=format&fit=crop&q=80', order: 6, isActive: true },
  { name: "Mother's Day", slug: 'mothers-day', badge: '🌸 For Ammi', imageUrl: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=800&auto=format&fit=crop&q=80', order: 7, isActive: true },
  { name: "Father's Day", slug: 'fathers-day', badge: '👔 For Abu', imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80', order: 8, isActive: true },
  { name: 'Graduation', slug: 'graduation', badge: '🎓 Success', imageUrl: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&auto=format&fit=crop&q=80', order: 9, isActive: true },
  { name: 'Friendship', slug: 'friendship', badge: '🤝 Best Friends', imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80', order: 10, isActive: true },
  { name: 'Corporate Gifts', slug: 'corporate-gifts', badge: '🏢 Executive', imageUrl: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=800&auto=format&fit=crop&q=80', order: 11, isActive: true },
  { name: 'Other Occasions', slug: 'other-occasions', badge: '🎁 Blessings', imageUrl: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=800&auto=format&fit=crop&q=80', order: 12, isActive: true },
];

export const INITIAL_GIFT_BOXES: Omit<GiftBox, 'id'>[] = [
  {
    name: 'Royal Emerald Velvet Keepsake Box',
    price: 1500,
    description: 'Rich deep emerald green velvet hard box with magnetic closure, satin lining, and gold foil embossed logo.',
    color: 'Emerald & Gold',
    dimensions: '30cm x 22cm x 10cm',
    imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    order: 1,
  },
  {
    name: 'Matte Black Luxury Executive Chest',
    price: 1800,
    description: 'Ultra-matte black rigid chest box with gold lock accent, textured finish, and crushed silk ribbon.',
    color: 'Matte Black & Gold',
    dimensions: '32cm x 24cm x 12cm',
    imageUrl: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    order: 2,
  },
  {
    name: 'Ivory & Rose Gold Celebration Box',
    price: 1400,
    description: 'Classic warm ivory box embossed with delicate floral motifs and tied with a 2-inch blush rose satin bow.',
    color: 'Ivory & Rose Gold',
    dimensions: '28cm x 20cm x 9cm',
    imageUrl: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    order: 3,
  },
  {
    name: 'Rustic Pine Wooden Hamper Crate',
    price: 2200,
    description: 'Handcrafted polished Pakistani pine wood box with brass clasp and laser-engraved calligraphy.',
    color: 'Natural Wood & Brass',
    dimensions: '35cm x 25cm x 14cm',
    imageUrl: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    order: 4,
  },
];

export const INITIAL_ANNOUNCEMENTS = [
  { id: 'ann_1', text: '✨ Free Nationwide Delivery across Pakistan on all orders over Rs. 4,500', link: '/shop', isActive: true, order: 1 },
  { id: 'ann_2', text: '🎁 Signature Customized Gift Boxes & Keepsake Wooden Crates Available', link: '/gift-box', isActive: true, order: 2 },
  { id: 'ann_3', text: '🔒 100% Verified Advance Bank Transfer — Safe & Secure Gifting Experience', link: '/terms', isActive: true, order: 3 },
  { id: 'ann_4', text: '🚚 Same-Day & Express Dispatch available in Lahore, Karachi & Islamabad', link: '/shipping', isActive: true, order: 4 },
];

export const INITIAL_TRUST_ITEMS = [
  { id: 'trust_1', title: 'Premium Luxury Quality', subtitle: 'Hand-inspected gifts & curated hampers', icon: 'Sparkles', isActive: true },
  { id: 'trust_2', title: 'Secure Advance Payment', subtitle: '100% verified Bank Transfer with receipt upload', icon: 'ShieldCheck', isActive: true },
  { id: 'trust_3', title: 'Bespoke Customization', subtitle: 'Custom boxes, satin ribbons & wax seal cards', icon: 'Gift', isActive: true },
  { id: 'trust_4', title: 'Reliable Pakistan Delivery', subtitle: 'Safe transit to 100+ cities nationwide', icon: 'Truck', isActive: true },
  { id: 'trust_5', title: 'Dedicated Customer Support', subtitle: 'Personalized gifting assistance', icon: 'Phone', isActive: true },
];

export const INITIAL_HERO_BANNERS = [
  {
    id: 'banner_1',
    title: 'Exquisite Gifting, Lovingly Curated',
    subtitle: 'Pakistan’s premier atelier for luxury perfumes, couple timepieces, handcrafted leather, and bespoke gift hampers.',
    ctaText: 'Explore Collection',
    ctaLink: '/shop',
    imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=1600&auto=format&fit=crop&q=85',
    badge: 'SIGNATURE LUXURY COLLECTION',
    isActive: true,
    order: 1,
  },
  {
    id: 'banner_2',
    title: 'Build Your Signature Gift Box',
    subtitle: 'Select from keepsake blush velvet boxes or polished wooden chests, handpick artisan items, and add handwritten gold calligraphy notes.',
    ctaText: 'Start Custom Box',
    ctaLink: '/gift-box',
    imageUrl: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=1600&auto=format&fit=crop&q=85',
    badge: 'BESPOKE GIFT BOX BUILDER',
    isActive: true,
    order: 2,
  },
  {
    id: 'banner_3',
    title: 'Celebration Gifting Delivered Across Pakistan',
    subtitle: 'Delight loved ones across Lahore, Karachi, Islamabad, and 100+ cities with prompt, delicate courier packaging.',
    ctaText: 'Shop Occasions',
    ctaLink: '/occasions',
    imageUrl: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=1600&auto=format&fit=crop&q=85',
    badge: 'NATIONWIDE LUXURY DELIVERY',
    isActive: true,
    order: 3,
  },
];

export const DEFAULT_HOMEPAGE_SECTIONS: HomepageSectionConfig[] = [
  {
    id: 'trust',
    name: 'Trust & Confidence Badges',
    isEnabled: true,
    order: 1,
    backgroundColor: '#360f1b',
    textColor: 'light',
  },
  {
    id: 'hero',
    name: 'Hero Banner Slider',
    isEnabled: true,
    order: 2,
  },
  {
    id: 'categories',
    name: 'Explore Gift Categories',
    isEnabled: true,
    order: 3,
    badge: 'CURATED GIFT DEPARTMENTS',
    title: 'Shop by Category',
    subtitle: 'Thoughtfully curated luxury gift collections for every relationship & milestone',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 88,
    backgroundOverlayColor: '#fdf5f7',
    backgroundPosition: 'center',
    textColor: 'dark',
  },
  {
    id: 'premium_collection',
    name: 'Signature Premium Collection',
    isEnabled: true,
    order: 4,
    badge: 'ROYAL ATELIER EDITION',
    title: 'The Royal Gifting Collection',
    subtitle: 'Exquisite artisanal attars, couple chronographs, and distinguished heirloom keepsakes',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 85,
    backgroundOverlayColor: '#280a13',
    backgroundPosition: 'center',
    textColor: 'light',
  },
  {
    id: 'occasions',
    name: 'Shop by Occasion',
    isEnabled: true,
    order: 5,
    badge: 'CELEBRATE LIFE’S MILESTONES',
    title: 'Gifts for Every Milestone',
    subtitle: 'Weddings, Anniversaries, Birthdays, Eid, and heartwarming celebrations across Pakistan',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 86,
    backgroundOverlayColor: '#fff4f6',
    backgroundPosition: 'center',
    textColor: 'dark',
  },
  {
    id: 'gift_boxes',
    name: 'Ready-to-Ship Luxury Gift Boxes',
    isEnabled: true,
    order: 6,
    badge: 'LUXURY PACKAGING',
    title: 'Luxury Keepsake Gift Boxes',
    subtitle: 'Rigid blush velvet keepsake chests and polished wooden boxes crafted to leave a lasting impression',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 84,
    backgroundOverlayColor: '#330c18',
    backgroundPosition: 'center',
    textColor: 'light',
    ctaText: 'Explore Gift Boxes',
    ctaLink: '/shop?category=Gift%20Boxes',
  },
  {
    id: 'personalized',
    name: 'Personalized & Monogrammed Gifts',
    isEnabled: true,
    order: 7,
    badge: 'BESPOKE ENGRAVING',
    title: 'Personalized & Bespoke Keepsakes',
    subtitle: 'Custom laser-engraved pens, initial-embossed leather, and wax-sealed calligraphy notes',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 88,
    backgroundOverlayColor: '#faf4f5',
    backgroundPosition: 'center',
    textColor: 'dark',
  },
  {
    id: 'box_builder',
    name: 'Signature Gift Box Builder Banner',
    isEnabled: true,
    order: 8,
    badge: 'INTERACTIVE ATELIER',
    title: 'Build Your Own Gift Box',
    subtitle: 'Select a luxury velvet or wooden box, choose artisan gifts, and write a personalized gift card note',
    ctaText: 'Start Building Your Box',
    ctaLink: '/gift-box',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 82,
    backgroundOverlayColor: '#360f1b',
    backgroundPosition: 'center',
    textColor: 'light',
  },
  {
    id: 'best_sellers',
    name: 'Best Sellers Showcase',
    isEnabled: true,
    order: 9,
    badge: 'MOST LOVED CHOICES',
    title: 'Most Loved Gifts',
    subtitle: 'Top rated gifts celebrating love, appreciation, and gratitude across Pakistan',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 88,
    backgroundOverlayColor: '#fdf5f7',
    backgroundPosition: 'center',
    textColor: 'dark',
  },
  {
    id: 'featured',
    name: 'Featured Products Showcase',
    isEnabled: true,
    order: 10,
    badge: 'CURATED SELECTIONS',
    title: 'Featured Gift Selections',
    subtitle: 'Handpicked luxury pairings curated by our master gifting atelier',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 86,
    backgroundOverlayColor: '#faf4f5',
    backgroundPosition: 'center',
    textColor: 'dark',
  },
  {
    id: 'sale',
    name: 'Special Celebration Offers',
    isEnabled: true,
    order: 11,
    badge: 'LIMITED TIME DELIGHT',
    title: 'Special Celebration Offers',
    subtitle: 'Exclusive limited-time savings on signature luxury gift selections',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 82,
    backgroundOverlayColor: '#2b0914',
    backgroundPosition: 'center',
    textColor: 'light',
  },
  {
    id: 'why_us',
    name: 'Why Choose MINAL KHAN',
    isEnabled: true,
    order: 12,
    badge: 'THE ATELIER STANDARD',
    title: 'The MINAL KHAN Distinction',
    subtitle: 'Unrivaled attention to detail in packaging, presentation, and delivery across Pakistan',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 85,
    backgroundOverlayColor: '#250812',
    backgroundPosition: 'center',
    textColor: 'light',
  },
  {
    id: 'track_order',
    name: 'Quick Order Tracking',
    isEnabled: true,
    order: 13,
    badge: 'REAL-TIME TRACKING',
    title: 'Track Your Gift Delivery',
    subtitle: 'Check the real-time courier status of your parcel anytime with your tracking ID',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 88,
    backgroundOverlayColor: '#fdf5f7',
    backgroundPosition: 'center',
    textColor: 'dark',
  },
  {
    id: 'reviews',
    name: 'Customer Appreciation & Reviews',
    isEnabled: true,
    order: 14,
    badge: 'VERIFIED DISPATCHES',
    title: 'Customer Appreciation',
    subtitle: 'Verified reviews from discerning gift-givers in Lahore, Karachi, Islamabad and beyond',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 88,
    backgroundOverlayColor: '#fdf8f9',
    backgroundPosition: 'center',
    textColor: 'dark',
  },
  {
    id: 'blogs',
    name: 'Gifting Ideas & Journal',
    isEnabled: true,
    order: 15,
    badge: 'EDITORIAL & INSPIRATION',
    title: 'The Gifting Journal',
    subtitle: 'Curated advice and inspirational guides on memorable Pakistani gifting',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 88,
    backgroundOverlayColor: '#faf5f6',
    backgroundPosition: 'center',
    textColor: 'dark',
  },
  {
    id: 'shipping',
    name: 'Delivery Information Banner',
    isEnabled: true,
    order: 16,
    badge: 'SAFE COURIER TRANSIT',
    title: 'Prompt Nationwide Delivery',
    subtitle: 'Dispatched securely to Karachi, Lahore, Islamabad, and 100+ cities nationwide',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 82,
    backgroundOverlayColor: '#330c18',
    backgroundPosition: 'center',
    textColor: 'light',
  },
  {
    id: 'faq',
    name: 'Frequently Asked Questions',
    isEnabled: true,
    order: 17,
    badge: 'COMMON INQUIRIES',
    title: 'Frequently Asked Questions',
    subtitle: 'Everything you need to know about our packaging, advance bank payment, and delivery',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 88,
    backgroundOverlayColor: '#fbf5f6',
    backgroundPosition: 'center',
    textColor: 'dark',
  },
  {
    id: 'concierge',
    name: 'VIP WhatsApp Concierge Support',
    isEnabled: true,
    order: 18,
    badge: 'PERSONAL CONCIERGE',
    title: 'VIP Gift Concierge & Support',
    subtitle: 'Need personalized gifting advice or corporate hamper quotes? Connect directly with our atelier',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=1600&auto=format&fit=crop&q=80',
    backgroundOverlayOpacity: 85,
    backgroundOverlayColor: '#280a13',
    backgroundPosition: 'center',
    textColor: 'light',
  },
];

export const INITIAL_REVIEWS: CustomerReview[] = [
  {
    id: 'rev_1',
    customerName: 'Ayesha Siddiqui',
    city: 'Lahore',
    rating: 5,
    comment: 'The Royal Emerald Keepsake box was beyond stunning! The perfume smelled heavenly and the gold card calligraphy was done with immense care. Highly recommended for anniversary surprises!',
    productName: 'Royal Cambodian Dehn Al Oud',
    date: '2025-01-14',
    isApproved: true,
    isFeatured: true,
  },
  {
    id: 'rev_2',
    customerName: 'Bilal Farooq',
    city: 'Karachi',
    rating: 5,
    comment: 'Ordered the couple chronograph set for my sister’s wedding. Payment verification took 10 minutes and the gift was delivered to Clifton the very next day. Flawless packaging!',
    productName: 'His & Hers Couple Chronograph Timepiece Set',
    date: '2025-01-20',
    isApproved: true,
    isFeatured: true,
  },
  {
    id: 'rev_3',
    customerName: 'Maham Tariq',
    city: 'Islamabad',
    rating: 5,
    comment: 'The custom gift box builder was so easy to use! I selected a velvet box, leather wallet, and chocolates. The receiver was overwhelmed with joy. True luxury standard in Pakistan.',
    productName: 'Executive Full-Grain Leather Bi-Fold Wallet',
    date: '2025-02-02',
    isApproved: true,
    isFeatured: true,
  },
  {
    id: 'rev_4',
    customerName: 'Usman Malik',
    city: 'Faisalabad',
    rating: 5,
    comment: 'First time ordering high-value gifts online with advance bank transfer. MINAL KHAN verified my transfer immediately and sent tracking. Item arrived in pristine condition.',
    productName: 'Emerald Cut Zircon & 18K Gold Plated Solitaire Pendant',
    date: '2025-02-10',
    isApproved: true,
    isFeatured: true,
  },
];

export const INITIAL_BLOGS: BlogPost[] = [
  {
    id: 'blog_1',
    title: 'How to Curate the Perfect Luxury Wedding Gift Box in Pakistan',
    slug: 'curate-luxury-wedding-gift-box-pakistan',
    excerpt: 'Explore thoughtful pairing ideas including oriental attars, couple chronographs, and customized keepsakes for Pakistani shadi celebrations.',
    content: `When selecting a wedding gift for a couple in Pakistan, timeless elegance matters more than fleeting trends. 

### 1. The Power of Keepsake Packaging
A luxury hard velvet or polished wooden chest immediately sets the tone. Unlike standard paper wraps, a keepsake box is preserved for years to hold wedding memorabilia, jewelry, and love letters.

### 2. Meaningful Pairing
Pairing a his-and-hers gift — such as matching wristwatches or twin perfume decanters — signifies unity. Adding artisanal Belgian chocolates or gold-leaf Medjool dates introduces traditional Pakistani warmth and sweetness (meetha).

### 3. Handwritten Calligraphy
Never rely on printed receipts. A gold-foil card hand-written with sincere prayers and du'as creates an emotional connection that outlives the event.`,
    imageUrl: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=800&auto=format&fit=crop&q=80',
    category: 'Gifting Guide',
    date: '2025-01-10',
    author: 'MINAL KHAN Atelier',
    readTime: '4 min read',
    published: true,
  },
  {
    id: 'blog_2',
    title: 'The Art of Artisanal Attars & Perfumes as Prestigious Gifts',
    slug: 'art-of-artisanal-attars-perfumes-prestigious-gifts',
    excerpt: 'Why Cambodian Oud, Taif Rose, and pure oriental perfumes remain the most prestigious gifts for Eid, father’s day, and milestone birthdays.',
    content: `Fragrance holds a profound place in Islamic and Pakistani heritage. Presenting a decanter of pure Cambodian Dehn Al Oud or artisanal floral attar carries deep respect and honor.

### Longevity and Projection
Unlike alcohol-heavy sprays that dissipate quickly, pure oil extractions mature on skin and fabrics over days, reminding the recipient of your thoughtful gesture with every subtle sillage.

### The Crystal Bottle Experience
A gift of perfume is incomplete without artisanal presentation. Our crystal cut flacons encased in velvet jewel boxes make a dignified statement on any vanity table.`,
    imageUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80',
    category: 'Fragrance',
    date: '2025-01-25',
    author: 'MINAL KHAN Atelier',
    readTime: '3 min read',
    published: true,
  },
];

export const INITIAL_FAQS: FAQItem[] = [
  {
    id: 'faq_1',
    question: 'How do I place an order on MINAL KHAN?',
    answer: 'Browse our collection or use our "Build Your Own Box" builder. Add your chosen items or custom box to the cart, fill out the delivery details, review our bank account details, and complete your order. After making the bank transfer, upload your receipt screenshot on checkout. Our team will verify and dispatch promptly.',
    category: 'Ordering',
    order: 1,
  },
  {
    id: 'faq_2',
    question: 'What payment methods do you accept? Is Cash on Delivery (COD) available?',
    answer: 'We operate strictly on 100% Verified Advance Bank Transfer. We do NOT offer Cash on Delivery (COD). This ensures that every luxury gift box is prepared fresh, customized with handwritten cards, and dispatched safely with premium courier care without risk of courier return or transit damage.',
    category: 'Payment',
    order: 2,
  },
  {
    id: 'faq_3',
    question: 'How long does delivery take across Pakistan?',
    answer: 'Orders for Lahore, Karachi, and Islamabad typically arrive within 1 to 2 business days. Delivery to other cities across Punjab, Sindh, KPK, and Balochistan takes 2 to 3 business days. All parcels are tracked and insured.',
    category: 'Delivery',
    order: 3,
  },
  {
    id: 'faq_4',
    question: 'Can I include a personalized handwritten message on the gift card?',
    answer: 'Yes, absolutely! Every gift box and individual gift order includes a complimentary luxury gold-embossed message card. You can provide your recipient’s name, your name, and your personal message during checkout or inside the Gift Box Builder.',
    category: 'Customization',
    order: 4,
  },
  {
    id: 'faq_5',
    question: 'Can I send a surprise gift directly to someone else without an invoice inside?',
    answer: 'Yes. Since all payments are completed via advance bank transfer, we never include any pricing or billing receipts inside the recipient’s package. The recipient only receives the pristine luxury gift with your personalized card.',
    category: 'Gifting',
    order: 5,
  },
];

export const DEFAULT_STORE_SETTINGS: StoreSettings = {
  whatsappNumber: '923001234567',
  whatsappHelpButtonText: 'Help & Support',
  whatsappHelpMessage: 'Assalam-o-Alaikum MINAL KHAN! I need assistance with gifts and delivery across Pakistan.',
  whatsappHelpEnabled: true,
  storeName: 'MINAL KHAN',
  tagline: 'Premium Gifts & Customized Gift Boxes',
  defaultLanguage: 'en',
  deliveryCharges: 250, // Standard PKR 250 delivery across Pakistan
  freeDeliveryThreshold: 4500, // Free delivery above Rs. 4,500
  estimatedDeliveryDays: '1 to 3 business days across Pakistan',
  shippingNotes: 'Packed in secure multi-layer bubble cushioning with branded MINAL KHAN seals.',
  contactEmail: 'orders@minalkhan.pk',
  contactPhone: '+92 300 1234567',
  address: 'Gulberg III, Lahore / Clifton, Karachi, Pakistan',
  announcement: '✨ Free Nationwide Delivery across Pakistan on all orders over Rs. 4,500',
  announcements: INITIAL_ANNOUNCEMENTS,
  trustItems: INITIAL_TRUST_ITEMS,
  heroBanners: INITIAL_HERO_BANNERS,
  heroAutoSlideDuration: 5,
  homepageSections: DEFAULT_HOMEPAGE_SECTIONS,
  themeSettings: {
    primaryColor: '#4a1525', // deep berry / contrast pink
    secondaryColor: '#c96f86', // dusty rose
    blushColor: '#fce7eb', // luxury blush pink
    accentColor: '#d4af37', // elegant gold
    creamBg: '#faf8f5', // warm cream
    charcoalText: '#1f181b', // charcoal text
    primaryGreen: '#4a1525',
    goldAccent: '#d4af37',
    blushPinkAccent: '#fce7eb',
  },
  bankDetails: {
    bankName: 'Meezan Bank Ltd / Bank Alfalah / HBL',
    accountTitle: 'MINAL KHAN GIFT STORE',
    accountNumber: '0102030405060708',
    iban: 'PK00MEZN0001020304050607',
    branch: 'Gulberg Main Boulevard Branch, Lahore',
    instructions: '1. Transfer the exact order total via online banking app, ATM, or counter transfer.\n2. Take a clear screenshot or photo of the payment receipt/transaction SMS.\n3. Upload the receipt file below before clicking "Place Order".\n4. Our finance team will verify the payment within 15-30 minutes and dispatch your order.',
    qrImageUrl: '',
    receiptRequired: true,
    isActive: true,
  },
  isInitialized: true,
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    name: 'Royal Cambodian Dehn Al Oud',
    price: 6500,
    salePrice: 5800,
    description: 'Aged pure artisanal Cambodian Agarwood attar in a crystal decanter with velvet packaging. Unmatched oriental longevity.',
    category: 'Perfumes',
    occasion: 'Eid',
    stock: 12,
    sku: 'MK-PRF-01',
    imageUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    isBestSeller: true,
    isGiftBoxEligible: true,
    badge: 'Bestseller',
    tags: ['Perfume', 'Oud', 'Luxury', 'Eid'],
    rating: 5.0,
    reviewCount: 38,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_2',
    name: 'Executive Full-Grain Leather Bi-Fold Wallet',
    price: 3200,
    salePrice: 2850,
    description: 'Handcrafted top-grain cowhide leather wallet with RFID blocking, dual currency compartments, and custom gold initials stamping option.',
    category: 'Wallets',
    occasion: "Father's Day",
    stock: 25,
    sku: 'MK-WLT-02',
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    isBestSeller: true,
    isPersonalized: true,
    isGiftBoxEligible: true,
    badge: 'Popular',
    tags: ['Wallet', 'Leather', 'Gifts For Him'],
    rating: 4.9,
    reviewCount: 29,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_3',
    name: 'His & Hers Couple Chronograph Timepiece Set',
    price: 9500,
    salePrice: 8500,
    description: 'Matching his and hers emerald dial quartz chronographs with stainless steel gold accents in a dual presentation box.',
    category: 'Watches',
    occasion: 'Anniversary',
    stock: 8,
    sku: 'MK-WCH-03',
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    isBestSeller: true,
    isGiftBoxEligible: true,
    badge: 'Anniversary Special',
    tags: ['Watches', 'Couple Gifts', 'Wedding'],
    rating: 5.0,
    reviewCount: 42,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_4',
    name: 'Artisanal Belgian Truffle & Medjool Dates Box (16 Pcs)',
    price: 3800,
    description: 'Handcrafted dark and hazelnut praline Belgian truffles paired with gold-leaf stuffed organic Medjool dates in an embossed keepsake box.',
    category: 'Chocolates',
    occasion: 'Birthday',
    stock: 20,
    sku: 'MK-CHC-04',
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    isBestSeller: true,
    isGiftBoxEligible: true,
    badge: 'Gourmet',
    tags: ['Chocolates', 'Dates', 'Sweets'],
    rating: 4.8,
    reviewCount: 31,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_5',
    name: 'Velvet Hatbox of 24 Long-Stem Red Roses',
    price: 4900,
    salePrice: 4200,
    description: 'Selected premium Dutch long-stem red roses arranged impeccably in a round black velvet hatbox tied with satin gold ribbon.',
    category: 'Flowers',
    occasion: "Valentine's Day",
    stock: 15,
    sku: 'MK-FLW-05',
    imageUrl: 'https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    isBestSeller: false,
    isGiftBoxEligible: false,
    badge: 'Fresh Blooms',
    tags: ['Flowers', 'Roses', 'Romance'],
    rating: 4.9,
    reviewCount: 22,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_6',
    name: 'Emerald Cut Zircon & 18K Gold Plated Solitaire Pendant',
    price: 4500,
    salePrice: 3900,
    description: 'Radiant emerald-cut created gemstone surrounded by AAA cubic zircon halo on a 925 sterling silver 18K gold-plated chain.',
    category: 'Jewellery',
    occasion: 'Engagement',
    stock: 14,
    sku: 'MK-JWL-06',
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    isBestSeller: false,
    isGiftBoxEligible: true,
    badge: 'Fine Jewellery',
    tags: ['Jewellery', 'Pendant', 'Silver', 'Gold'],
    rating: 5.0,
    reviewCount: 19,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_7',
    name: 'Hand-Calligraphed Gold Foil Ceramic Mug & Warmer',
    price: 2400,
    description: 'Handmade ceramic mug with celebratory calligraphy in 24k real gold luster, complete with smart electric temperature heating coaster.',
    category: 'Mugs',
    occasion: 'Corporate Gifts',
    stock: 30,
    sku: 'MK-MUG-07',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: false,
    isBestSeller: false,
    isPersonalized: true,
    isGiftBoxEligible: true,
    badge: 'Custom Mug',
    tags: ['Mugs', 'Calligraphy', 'Ceramics'],
    rating: 4.7,
    reviewCount: 16,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_8',
    name: 'Custom Engraved Brass Ballpoint Pen & Card Case',
    price: 2800,
    description: 'Heavyweight brass ballpoint pen with custom laser engraving, packaged with genuine leather pocket card holder in gift box.',
    category: 'Personalized Gifts',
    occasion: 'Graduation',
    stock: 22,
    sku: 'MK-PRS-08',
    imageUrl: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: false,
    isBestSeller: false,
    isPersonalized: true,
    isGiftBoxEligible: true,
    badge: 'Personalized',
    tags: ['Engraved', 'Pen', 'Corporate', 'Graduation'],
    rating: 4.8,
    reviewCount: 14,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_9',
    name: 'Imperial Taif Rose & Ambergris Attar in Crystal Decanter',
    price: 5200,
    salePrice: 4700,
    description: 'Distilled pure Taif rose petals infused with warm ambergris, presented in a diamond-faceted crystal bottle with silk tassel.',
    category: 'Perfumes',
    occasion: 'Wedding',
    stock: 10,
    sku: 'MK-PRF-09',
    imageUrl: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    isBestSeller: true,
    isGiftBoxEligible: true,
    badge: 'Luxury Essence',
    tags: ['Perfumes', 'Attar', 'Rose', 'Wedding'],
    rating: 4.9,
    reviewCount: 27,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_10',
    name: 'Silk Jacquard Shawl & 24K Gold-Plated Brooch Set',
    price: 6800,
    salePrice: 5900,
    description: 'Handwoven soft Kashmiri-inspired silk jacquard wrap paired with an artisanal filigree brooch in an ivory presentation chest.',
    category: 'Accessories',
    occasion: "Mother's Day",
    stock: 14,
    sku: 'MK-ACC-10',
    imageUrl: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    isBestSeller: false,
    isGiftBoxEligible: true,
    badge: 'Artisan Wrap',
    tags: ['Accessories', 'Shawl', 'Brooch', 'For Her'],
    rating: 5.0,
    reviewCount: 18,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_11',
    name: 'Handcrafted Polished Sheesham Wood Keepsake Chest',
    price: 4200,
    description: 'Pure solid Pakistani sheesham wood organiser with brass inlays, velvet interior compartments, and antique latch.',
    category: 'Gift Boxes',
    occasion: 'Anniversary',
    stock: 16,
    sku: 'MK-BOX-11',
    imageUrl: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    isBestSeller: true,
    isPersonalized: true,
    isGiftBoxEligible: false,
    badge: 'Handcrafted Wood',
    tags: ['Gift Boxes', 'Woodwork', 'Keepsake', 'Bespoke'],
    rating: 4.9,
    reviewCount: 35,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod_12',
    name: 'Gold Monogrammed French Macaron & Truffle Tower',
    price: 3600,
    description: 'Assortment of 12 delicate French almond macarons and 6 salted caramel truffles in a tiered hexagonal pink gift cylinder.',
    category: 'Chocolates',
    occasion: 'Birthday',
    stock: 25,
    sku: 'MK-CHC-12',
    imageUrl: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=800&auto=format&fit=crop&q=80',
    isActive: true,
    isFeatured: true,
    isBestSeller: false,
    isGiftBoxEligible: true,
    badge: 'Delight',
    tags: ['Chocolates', 'Macarons', 'Birthday', 'Sweets'],
    rating: 4.8,
    reviewCount: 20,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
];
